#ifndef FREERTOS_INC_EVENT_FRAMEWORK_H_
#define FREERTOS_INC_EVENT_FRAMEWORK_H_

#include "modules.h"

typedef enum {
	SIG_INIT,
	SIG_CONFIGURING_INIT,
	SIG_CONFIGURING_FINISH,
	SIG_LEARNING_INIT,
	SIG_LEARNING_WAITING_GREEN_LIGHT,
	SIG_LEARNING_WAITING_RED_LIGHT,
	SIG_LEARNING_FINISH,
	SIG_RUNNING_INIT,
	SIG_RUNNING_FINISH,
	SIG_TIMEOUT,
	SIG_LIGHT_ON,
	SIG_LIGHT_OFF
} signal_t;


#endif /* FREERTOS_INC_EVENT_FRAMEWORK_H_ */
