#ifndef FREERTOS_TEST_SUPPORT_FAKE_DATA_H_
#define FREERTOS_TEST_SUPPORT_FAKE_DATA_H_

TaskHandle_t sendStatusToEthernetHandle;
TaskHandle_t ligthYellowTaskHandle;
TaskHandle_t ligthGreenTaskHandle;
TaskHandle_t ligthRedTaskHandle;
TaskHandle_t sendTaskHandle;
TaskHandle_t esp01TaskHandle;
TaskHandle_t blinkLedConfigurationTaskHandle;

SemaphoreHandle_t xsGreenLightOff;
SemaphoreHandle_t xsGreenLigthOn;

#endif /* FREERTOS_TEST_SUPPORT_FAKE_DATA_H_ */
